### ISSUE TITLE
[suggestion] Mark calculated values

### ISSUE THREAD

**Issue by benni336** [bohdan-s/SunGather#16]
Hi all,
I would like to suggest to mark the calculated values that are not originally provided by the inverter for example with an prefix like "calc_".

This is an suggestion. I could do of course for my own version but I would prefere to development forces joined.

**Comment by bohdan-s** [comment]
@benni336 hi, sounds simple but its not. Some values are provided by some models, but for other models I am calculating the value.
e.g. load_power, since I want to keep the registers simple I dont want to have the possibility of calc_load_power or load_power as it makes the config confusing for new users.
v0.3.0 I just pushed now shows address or ---- if calculated in the console and web-server so this might help enough?
